### ISSUE TITLE
Transparenter  Hintergrund

### ISSUE THREAD

**Issue by DUiSBURGO** [roflrolle/Scriptable#3]
Sorry das ich nochmal nerve. Da es dein Code ist bin ich wohl hier an der richtigen Stelle 😅

würde gerne den Hintergrund von schwarz auf transparent ändern. 

`let fm = FileManager.iCloud();
let path = fm.documentsDirectory() + "/<your image name>.jpg";
// Image.fromFile(path) can also be used
w.backgroundImage = fm.readImage(path);`

mit dem Code funktioniert es nicht… 
Kannst danach diese Frage löschen 😅

**Comment by roflrolle** [comment]
Das issue muss ich schließen als "nicht weiterverfolgt".

Das Widget ist geschrieben so das es mit einer Hintergrund Farbe läuft.

Für den transparenten Effekt musst du dir erst ein Bild erstellen und es dann als Hintergrund einsetzen. 

Dein Code ist nur ein minimaler Ausschnitt was zu tun ist.

Anbei ein Beispiel wie es geht:

https://gist.github.com/mzeryck/3a97ccd1e059b3afa3c6666d27a496c9

**Comment by DUiSBURGO** [comment]
Das Script von mzeryck habe ich schon benutzt. Jetzt fehlt nur das ein pflegen des Bildes. Ja ich weiß das der Hintergrund auf schwarz ist, diesen kann ich auch in alle Farben ändern

**Comment by roflrolle** [comment]
Zeile 37 musste löschen und dann dein w.background... durch list.background... ersetzen.

Und in den vorherigen Statement sollte halt dein dareinfand passen 😉

**Comment by DUiSBURGO** [comment]
Also` List.backgroundcolor = new  Color ` muss ich löschen? 
bei mir werden leider keine Zeilen angezeigt 😂 oder ich stelle mich blöd an 

kannst du mir nicht zeigen wie der Code geht? 
Bild ist in Datein> iCloud > Scriptable abgespeichert

**Comment by roflrolle** [comment]
Ja das musste löschen:

````javascript
list.backgroundColor = new Color(color_bg)
````

Und ersetzen mit:

````javascript
let fm = FileManager.iCloud()
let mypath = fm.documentsDirectory() +"/<your image name>.jpg"
fm.downloadFileFromiCloud(mypath)
list.backgroundImage =fm.readImage(mypath)

````
