### ISSUE TITLE
Datenzugriffsfehler

### ISSUE THREAD

**Issue by torth** [roflrolle/Scriptable#5]
Nach dem Update auf iOS 16.4 erscheint eine Exception:
Error: Datenzugriffsfehler

**Comment by roflrolle** [comment]
Hab's geprüft und das ist ein Fehler in scriptable oder iOS 16.4

Der Fehler wird auf vielen scriptable Websites gemeldet, leider ohne Lösung.

Das muss leider scriptable oder Apple lösen 😥
